### PR TITLE
Add a vuepress blog theme by vuepress-theme-plume

### PR DESCRIPTION
**Pull request by pengzhanbo**

### CODE REVIEW

**Comment by Mister-Hope** [comment]
Same, en docs, also theme config is broken

**Comment by pengzhanbo** [comment]
Theme config is broken ? You mean site not found ? Please tell me details.

About En docs, emmm... 
At current stage, I have no plans to support En Docs.

**Comment by Mister-Hope** [comment]
image
image
image

Try ensure all your links are available.

**Comment by pengzhanbo** [comment]
Thanks, I have checked and fixed it

**Pull request merged**
